### ISSUE TITLE
Resource Generation via OAS

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/docs.kuadrant.io#65]
Epic to capture issues relating to this feature

- [x] https://github.com/Kuadrant/kuadrantctl/issues/52
- [x] https://github.com/Kuadrant/kuadrantctl/issues/53
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/63
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/64
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/82
