### ISSUE TITLE
API Observability Docs

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/docs.kuadrant.io#67]
(corresponding dev issues https://github.com/Kuadrant/kuadrant-operator/issues/439)

Dashboards
- [x]  https://github.com/Kuadrant/docs.kuadrant.io/issues/66
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/69

Alerts:
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/73

Tracing:
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/70

Metrics and dashboard guidelines:
- [x] https://github.com/Kuadrant/docs.kuadrant.io/issues/74
